"""add content blocks, attachments, hostel image key

Revision ID: 07fb0d35a995
Revises: 9b6a8f7a4641
Create Date: 2026-09-25 22:21:02.181890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07fb0d35a995'
down_revision: Union[str, None] = '9b6a8f7a4641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('content_blocks', sa.JSON(), nullable=True))
    op.add_column('chat_messages', sa.Column('attachments', sa.JSON(), nullable=True))
    op.add_column('hostels', sa.Column('image_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostels', 'image_key')
    op.drop_column('chat_messages', 'attachments')
    op.drop_column('chat_messages', 'content_blocks')
    # ### end Alembic commands ###
