"""add student is_admin flag

Revision ID: 9b6a8f7a4641
Revises: 59edf8f9d423
Create Date: 2026-09-25 21:44:47.148573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6a8f7a4641'
down_revision: Union[str, None] = '59edf8f9d423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default is required here (not just the model's Python-side
    # default) so this NOT NULL column can be added to a table that
    # already has rows.
    op.add_column(
        'students', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('students', 'is_admin', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_admin')
    # ### end Alembic commands ###
